---
title: "Data Exploration"
author: "Megan Lundequam, Casey Slaught, and Same Vanasse"
date: "3/30/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(kableExtra)
library(knitr)
library(lubridate)

```

## Creating plots

Creating plots to display the breakdown of number of generators and energy capacity of generators to show difference

```{r MAKING PLOTS - KEEP, warning=FALSE}
# install.packages("viridis")
# install.packages("RColorBrewer")
# install.packages("colormap")
library(viridis)
library(RColorBrewer)
library(colormap)
library(tidyverse)
library(ggplot2)
#install.packages("ggridges")
library(ggridges)
library(dplyr)
library(lubridate)
library(corrplot)
library(cowplot)

# creating plots

## Plot - number of generators by fuel type
Renewable.v.ff.gen <-
  ggplot(data = full.data.gen, mapping = aes(x = FuelType, fill = Renewable.v.FossilFuel)) +
  geom_bar() +
  labs(title = "Number of Generators by Fuel Type",
       y = "Count", x = "Energy Generation Type") +
  theme(axis.text.x = element_text(angle = 45,  hjust = 1))
print(Renewable.v.ff.gen)

ggsave("./Output/RvFPlot_Gen.jpg", Renewable.v.ff.gen, dpi = 300)

## Plot - nameplate capacity by fuel type
aggregated.gen.data.2 <- 
  full.data.gen %>%
  group_by(County, Renewable.v.FossilFuel, FuelType) %>%
  dplyr::summarise(total.np.cap = sum(Nameplate.Capacity1))

write.csv(aggregated.gen.data.2, row.names = FALSE, 
          file = "./Data/Processed/NPCapByFuelType.csv")

Renewable.v.ff.cap <-
  ggplot(data = aggregated.gen.data.2) +
  geom_col(mapping = aes(x = FuelType, y = total.np.cap, fill = Renewable.v.FossilFuel)) +
  labs(title = "Nameplate Capacity by Fuel Type",
       y = "Nameplate Capacity (MW)", x = "Energy Generation Type") +
  theme(axis.text.x = element_text(angle = 45,  hjust = 1))
print(Renewable.v.ff.cap)

ggsave("./Output/RvFPlot_Cap.jpg", Renewable.v.ff.cap, dpi = 300)


```

```{r summary tables - did not include in final report}
library(tidyverse)
library(dplyr)
library(kableExtra)
library(knitr)
library(lubridate)

# creating columns with generators for each fuel type by county
fueltype.per.county.spread <-
  pivot_wider(fueltype.per.county, names_from = FuelType, values_from = n)

# creating column with total number of generators by county
county.gen.summary <-
  fueltype.per.county %>%
  group_by(County) %>%
  summarise(gen_per_county = sum(n)) %>%
  ungroup()

county.gen.summary <-
  aggregated.gen.data.2 %>%
  group_by(County,Renewable.v.FossilFuel) %>%
  summarise()
  mutate(
    Percent_Renewable
  )
  
knitr::kable(aggregated.gen.data.2)

```