---
title: "Data Wrangling"
author: "Megan Lundequam, Same Vanasse and Casey Slaught"
date: "3/30/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plyr)
library(sf)
library(tidycensus)
library(tidyr)
library(tidyverse)
options(tigris_use_cache = TRUE)
library(scales)
library(sf)
library(dplyr)
library(lubridate)
library(corrplot)


theme_set(theme_classic())
```

```{r}
## Census Data
allCensusVariables = load_variables(2020, "acs5", cache=TRUE)
View(allCensusVariables)

##Names are not descriptive, but did not want to manipulate code too much so I simply applied new code numbers to the old names and will reclassify them later.

#'Mobility' ~ B07012_002 ~ Below 100 percent of the poverty level --GEOGRAPHICAL MOBILITY IN THE PAST YEAR BY POVERTY STATUS IN THE PAST 12 MONTHS FOR                                   CURRENT RESIDENCE IN THE UNITED STATES
#'Mobility2' ~ B07004B_001 GEOGRAPHICAL MOBILITY IN THE PAST YEAR (BLACK OR AFRICAN AMERICAN ALONE) FOR CURRENT RESIDENCE IN THE UNITED STATES
#'RaceAllocation' ~ B07404A_001 GEOGRAPHICAL MOBILITY IN THE PAST YEAR (WHITE ALONE) FOR RESIDENCE 1 YEAR AGO IN THE UNITED STATES
#'DetailedRace' ~ B23006_016 Some college or associate's degree --EDUCATIONAL ATTAINMENT BY EMPLOYMENT STATUS FOR THE POPULATION 25 TO 64 YEARS




UpdatedCensus = st_read("../Data/Processed/NC_county_complete3.geojson")
UpdatedCensusNoGeometry = st_drop_geometry(UpdatedCensus)

write.csv(UpdatedCensusNoGeometry, row.names = FALSE, 
          file = "../Data/Processed/UpdatedCensus.csv")
```


```{r}
## Adding new census info and cleaning it
additional.census <- read.csv("../Data/Processed/UpdatedCensus.csv", stringsAsFactors = TRUE) 
additional.census <- 
  additional.census %>%
  subset(select=c(County, TotalPopulation, NoSchooling, Mobility, RaceAllocation, DetailedRace)) %>%
  rename(c("PovertyMobility" = Mobility, "WhitePopMobility" = RaceAllocation, "CollegeDeg" = DetailedRace)) %>%
  mutate(Per.PovertyMobility = (PovertyMobility/TotalPopulation),
         MinorityMobility = (TotalPopulation - WhitePopMobility),
         Per.MinorityMobility = (MinorityMobility/TotalPopulation),
         Per.NoSchooling = (NoSchooling/TotalPopulation),
         Per.CollegeDeg = (CollegeDeg/TotalPopulation)
         )

## Generator Info
census.data <- read.csv("../Data/Processed/generatorsCensusCategoriesComplete.csv", stringsAsFactors = TRUE)
census.data <- 
  full_join(census.data, additional.census) %>%
  drop_na(Energy.Source.1)

## Getting nameplate capacity
generator.data <- read.csv("../Data/2020EnergyData/3_1_Generator_Y2020.csv", stringsAsFactors = TRUE)

## Selecting variables of interest
generator.data <- 
  generator.data %>%
  subset(generator.data$State == "NC") %>%
  subset(select = c(County, Plant.Code, Prime.Mover, Nameplate.Capacity..MW.))

## Adding income to the full generator data by county
full.data <- cbind(census.data, generator.data$Nameplate.Capacity..MW.) %>% 
  rename(c("Nameplate.Capacity" = `generator.data$Nameplate.Capacity..MW.`)) %>% 
  mutate(Nameplate.Capacity1 = as.numeric(as.character(Nameplate.Capacity)))

```


```{r}
## Aggregating the generator data so that it groups all of it by county and by generation type
aggregated.gen.data <- 
  full.data %>%
  group_by(County, Renewable.v.FossilFuel) %>%
  dplyr::summarise(energy.type.gen = sum(Nameplate.Capacity1))

## Joining it to the census data to have capacity and income in same file & selecting specific variables
processed.gen.census <- 
  full_join(aggregated.gen.data, census.data) %>%
  subset(select=c(County, Renewable.v.FossilFuel, energy.type.gen, MedianHouseholdIncome, TotalPopulation, Per.CollegeDeg, Per.PovertyMobility, Per.MinorityMobility, Per.NoSchooling)) %>%
  distinct(.keep_all = TRUE)

## Creating a total generation variable, Removing fossil vs renewable distinction
total.gen.census <- 
  processed.gen.census %>%
  group_by(County) %>%
  dplyr::summarise(total.gen = sum(energy.type.gen))

##Separating into 3 different data sets to analyse different impacts
Final.gen.census <-
  full_join(processed.gen.census, total.gen.census) 

Renewable.county <- 
  Final.gen.census %>%
  subset(Renewable.v.FossilFuel=='Renewable Fuel') 

Fossil.county <- 
  Final.gen.census %>%
  subset(Renewable.v.FossilFuel=='Fossil Fuel') 
```

```{r}
## Correlation Plot
Corr.data <- 
  Renewable.county %>%
  select(MedianHouseholdIncome:total.gen) %>%
  na.omit() %>%
  subset(select=-c(County))

corrplot(Corr.data, method = "ellipse")
corrplot.mixed(Corr.data, upper = "ellipse")

## All variable Regression
regression.variables <- 
  lm(data = Final.gen.census, log(total.gen) ~ log(MedianHouseholdIncome) + 
       Per.CollegeDeg + Per.PovertyMobility + 
       Per.MinorityMobility)

## AIC
step(regression.variables)

## Regression Analysis
total.energy.reg <- 
  lm(data = Final.gen.census, log(total.gen) ~ log(MedianHouseholdIncome) + 
       Per.CollegeDeg + Per.PovertyMobility + 
       Per.MinorityMobility)
summary(total.energy.reg)


fossil.reg <- 
  lm(data = Fossil.county, log(energy.type.gen) ~ log(MedianHouseholdIncome) + 
       Per.CollegeDeg + Per.PovertyMobility + 
       Per.MinorityMobility)
summary(fossil.reg)

renewable.reg <- 
  lm(data = Renewable.county, log(energy.type.gen) ~ log(MedianHouseholdIncome) + 
       Per.CollegeDeg + Per.PovertyMobility + 
       Per.MinorityMobility)
summary(renewable.reg)


plot(renewable.reg)
plot(total.energy.reg)
plot(fossil.reg)


```



