---
title: "Wrangling_ML"
author: "Megan Lundequam & Same Vanasse & Casey Slaught"
date: "4/11/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Set up your session

```{r, message = FALSE}
getwd()
library(plyr)
library(tidyverse)
library(lubridate)
library(dplyr)


```

## Wrangling
```{r}
energy.data.plant <- read.csv("../Data/Raw/2___Plant_Y2020_ready.csv", fileEncoding='UTF-8-BOM')

colnames(energy.data.plant)

summary(energy.data.plant$State)

# Select NC and data of interest
energy.data.plant.NC <- filter(energy.data.plant, State == "NC")

energy.data.plant.NC.locations <- select(energy.data.plant.NC, Utility.ID, Utility.Name, Plant.Code, Plant.Name, City, State, County, Latitude, Longitude, Primary.Purpose..NAICS.Code.)

```

```{r}
energy.data.generator <- read.csv("../Data/Raw/3_1_Generator_Y2020.csv", fileEncoding='UTF-8-BOM')

energy.data.generator.NC <- filter(energy.data.generator, State == "NC")
energy.data.generator.NC.type <- select(energy.data.generator.NC, Utility.ID, Utility.Name, Plant.Code, Plant.Name, State, County, Technology, Energy.Source.1)
```

```{r}
#joining
energy.data.plant.generator.NC <- left_join(energy.data.generator.NC.type, energy.data.plant.NC.locations, by = "Plant.Code")

```

```{r}
# Save processed file
write.csv(energy.data.plant.generator.NC, row.names = FALSE, 
          file = "../Data/Processed/longlat_generators_NC.csv")

```

## Creating a spatial dataframe from coordinate columns

```{r Create a spatial dataframe from coordinate data}

library(sf)
library(ggplot2)

#Read in our processed EPA Air dataset, setting the Date column to be dates
NCGenerators <- read.csv("../Data/Processed/longlat_generators_NC", stringsAsFactors = TRUE)

#Wrangle so each site has only one record, computing mean ozone and PM2.5 at that site
#EPAair.sites <- EPAair %>% 
 # group_by(Site.Name, COUNTY, SITE_LATITUDE, SITE_LONGITUDE) %>% 
 # summarize(
  #  mean_Ozone = mean(Ozone, na.rm=T),    #What does "na.rm=T" do? Is it necessary? 
   # mean_PM25 = mean(PM2.5, na.rm=T),
   # count_all = n(),
  #  count_Ozone = sum(!is.na(Ozone)),
  #  count_PM25 = sum(!is.na(PM2.5)))

#Convert to a spatial dataframe
NCGenerators.sf <- NCGenerators %>% 
  st_as_sf(coords = c('Longitude','Latitude'),
           crs=4326) #this command creates this table as a simple feature. tell the code what to use as x and y coordinates and specify coordinate reference system 4326
st_write(NCGenerators.sf, "../Data/Processed/generators.geojson")


ggplot() + geom_sf(data=NCGenerators.sf,aes(color= Technology))
#View the data using the methods above...

```



categorize 
```{r}
generatorsCensus2020 = st_read("../Data/Processed/generatorsCensus2020.geojson")
generatorsCensusNoGeometry = st_drop_geometry(generatorsCensus2020)
summary(as.factor(generatorsCensusNoGeometry$Energy.Source.1))

# adding "Fuel Type" column according to reference table 28 of LayoutY2020

generatorsCensusCategories <- generatorsCensusNoGeometry %>%
  mutate(
    Fuel.Type = case_when(
      Energy.Source.1 == "AB" ~ "Solid Renewable Fuel",
      Energy.Source.1 == "BIT" ~ "Coal",
      Energy.Source.1 == "BLQ" ~ "Liquid Renewable Fuel",
      Energy.Source.1 == "DFO" ~ "Petroleum Product",
      Energy.Source.1 == "LFG" ~ "Gaseous Renewable Fuel",
      Energy.Source.1 == "MWH" ~ "Energy Storage",
      Energy.Source.1 == "NG" ~ "Natural Gas",
      Energy.Source.1 == "NUC" ~ "Nuclear",
      Energy.Source.1 == "OBG" ~ "Gaseous Renewable Fuel",
      Energy.Source.1 == "SUN" ~ "Solar",
      Energy.Source.1 == "WAT" ~ "Hydroelectric",
      Energy.Source.1 == "WDS" ~ "Solid Renewable Fuel",
      Energy.Source.1 == "WH" ~ "Waste Heat",
      Energy.Source.1 == "WND" ~ "Wind")
  )

summary(as.factor(generatorsCensusCategories$Fuel.Type))

# adding renewable v fossil fuel column according to reference table 28 of LayoutY2020
generatorsCensusCategoriesComplete <- generatorsCensusCategories %>%
  mutate(
    Renewable.v.FossilFuel = case_when(
      Fuel.Type == "Coal" ~ "Fossil Fuel",
      Fuel.Type == "Energy Storage" ~ "Other",
      Fuel.Type == "Gaseous Renewable Fuel" ~ "Renewable Fuel",
      Fuel.Type == "Hydroelectric" ~ "Renewable Fuel",
      Fuel.Type == "Liquid Renewable Fuel" ~ "Renewable Fuel",
      Fuel.Type == "Natural Gas" ~ "Fossil Fuel",
      Fuel.Type == "Nuclear" ~ "Nuclear",
      Fuel.Type == "Petroleum Product" ~ "Fossil Fuel",
      Fuel.Type == "Solar" ~ "Renewable Fuel",
      Fuel.Type == "Solid Renewable Fuel" ~ "Renewable Fuel",
      Fuel.Type == "Waste Heat" ~ "Other",
      Fuel.Type == "Wind" ~ "Renewable Fuel"
    )
  )

summary(as.factor(generatorsCensusCategoriesComplete$Renewable.v.FossilFuel))

write.csv(generatorsCensusCategoriesComplete, row.names = FALSE, 
          file = "../Data/Processed/generatorsCensusCategoriesComplete.csv")

```

```{r}

additional.census <- read.csv("../Data/Processed/UpdatedCensus.csv", stringsAsFactors = TRUE) 

## Generator Info
census.data <- read.csv("../Data/Processed/generatorsCensusCategoriesComplete.csv", stringsAsFactors = TRUE)

## Getting nameplate capacity
generator.data <- read.csv("../Data/2020EnergyData/3_1_Generator_Y2020.csv", stringsAsFactors = TRUE)

## Selecting variables of interest
generator.data <- 
  generator.data %>%
  subset(generator.data$State == "NC") %>%
  subset(select = c(County, Plant.Code, Prime.Mover, Nameplate.Capacity..MW.))

## Adding income to the full generator data by county
full.data <- cbind(census.data, generator.data$Nameplate.Capacity..MW.) %>% 
  dplyr::rename(c("Nameplate.Capacity" = `generator.data$Nameplate.Capacity..MW.`)) %>% 
  dplyr::mutate(Nameplate.Capacity1 = as.numeric(as.character(Nameplate.Capacity)))

## Aggregating the generator data so that it groups all of it by county and by generation type
aggregated.gen.data <- 
  full.data %>%
  group_by(County, Renewable.v.FossilFuel) %>%
  dplyr::summarise(energy.type.gen = sum(Nameplate.Capacity1))

## Data table with just the number of generators in each county divided out by renewable v ff
gen.per.county <- 
  full.data %>%
  group_by(County, Renewable.v.FossilFuel) %>%
  dplyr::summarise(Number.of.Generators = n())

#saving file
write.csv(gen.per.county, row.names = FALSE, 
          file = "../Data/Processed/NumberGeneratorsPerCounty.csv")


# Data table with the breakdown of energy type in each county
fueltype.per.county <- 
  full.data %>%
  count(County, FuelType)

```


``` {r}

#making plots with data


```

``` {r dont run - this is a fail}
## failed attempt
generators.per.county <-
  aggregated.gen.data.plant.total %>%
  group_by(County, Renewable.v.FossilFuel) %>%
  #dplyr::mutate(Num.Gen = as.numeric(as.character(Number.of.Generators$Number.of.Generators.freq)))
  dplyr::mutate(Total.Generators = group_keys(aggregated.gen.data.plant.total$.rows))

##
generators.per.county.join <-
  full_join(aggregated.gen.data.plant.total, group_keys(Number.of.Generators))


generators.per.county <-
  aggregated.gen.data.plant.total %>%
  group_by(County, Renewable.v.FossilFuel) %>%
  dplyr::summarise(Generators = n())

## Aggregating the generator data so that it groups all of it by county and by number of plants
aggregated.gen.data.plant.total <- 
  full.data %>%
  group_by(County, Renewable.v.FossilFuel) %>%
  dplyr::summarise(Number.of.Generators = count(Plant.Name))
```


