---
title: "Data Wrangling"
author: "Megan Lundequam, Same Vanasse and Casey Slaught"
date: "3/30/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plyr)
library(sf)
library(tidycensus)
library(tidyr)
library(tidyverse)
options(tigris_use_cache = TRUE)

census_api_key("a8cad28557bae7c89aae6ea747549dd4816c6fbd")
```

```{r}
allCensusVariables = load_variables(2020, "acs5", cache=TRUE)
# View(allCensusVariables)

censusVariables = c(
  "MedianFamilyIncome" = "B19113_001",
  "TotalPopulation" = "B25026_001", # in occupied housing units
  "BlackPopulation" = "C02003_004", # one race
  "WhitePopulation" = "C02003_003", # one race
  "NativeAmerican Population" = "C02003_005", # one race
  "NoSchooling" = "B15003_002",
  "Mobility" = "B07012_002",
  "Mobility2" = "B07004B_001",
  "RaceAllocation" = "B07404A_001",
  "DetailedRace" = "B23006_016"
)
```


```{r census}
# American Community Survey (ACS) has data on income, decennial does not
# ACS has yearly data, decennial is every 10 years

getCensusIncomeData = function(variableName, geography="county", state="NC", year=2020) {
  # gets ACS census data from 2010 to 2020
  
  variable = censusVariables[variableName]
  # TODO: add more census variables
  
  data = get_acs(state=state,
                 geography=geography,
                 year=year,
                 geometry=TRUE,
                 variables=variable) %>%
    select(GEOID, NAME, estimate, geometry) %>%
    mutate(Year=year) %>%
    plyr::rename(., c(estimate=variableName))
  
  if (geography == "state") {
    data = data %>% mutate(State=state.abb[match(NAME, state.name)])
  } else if (geography == "county") {
    data = data %>%
      separate(NAME, c("County", "State"), sep=", ", remove=F) %>%
      separate(County, c("CountyShort", NA), sep=" County", remove=F)
  }
   
  data = data[order(data$NAME),]
  data
}


income = getCensusIncomeData("MedianFamilyIncome")
population = getCensusIncomeData("TotalPopulation") %>% select(TotalPopulation)
noSchooling = getCensusIncomeData("NoSchooling") %>% select(NoSchooling)
mobility1 = getCensusIncomeData("Mobility") %>% select(Mobility)
mobility2 = getCensusIncomeData("Mobility2") %>% select(Mobility2)
raceAllocation = getCensusIncomeData("RaceAllocation") %>% select(RaceAllocation)
detailedRace = getCensusIncomeData("DetailedRace") %>% select(DetailedRace)

allData = cbind(income, population, noSchooling, mobility1, mobility2, raceAllocation, detailedRace)

allData = allData %>%
  select(-num_range(prefix = "geometry.", range=1:6))


# convert to regular object then back to sf?

## Sam ~ I changed the name to NC_county_comoplete2 so I could make as few changes as possible. I also kept the names of the variables the same for the same reason, though the values are updated. I have correct names in my own code.
filePath = "../Data/Processed/NC_county_complete3.geojson"
st_write(allData, filePath)

```

```{r}

generatorsNc = read.csv("../Data/Processed/longlat_generators_NC.csv") %>%
  st_as_sf(coords = c('Longitude','Latitude'), crs=4269) %>%
  plyr::rename(., c(County.x="CountyShort")) %>% 
  mutate(FuelType=case_when(
      Energy.Source.1 == "AB" ~ "Solid Renewable Fuel",
      Energy.Source.1 == "BIT" ~ "Coal",
      Energy.Source.1 == "BLQ" ~ "Liquid Renewable Fuel",
      Energy.Source.1 == "DFO" ~ "Petroleum Product",
      Energy.Source.1 == "LFG" ~ "Gaseous Renewable Fuel",
      Energy.Source.1 == "MWH" ~ "Energy Storage",
      Energy.Source.1 == "NG" ~ "Natural Gas",
      Energy.Source.1 == "NUC" ~ "Nuclear",
      Energy.Source.1 == "OBG" ~ "Gaseous Renewable Fuel",
      Energy.Source.1 == "SUN" ~ "Solar",
      Energy.Source.1 == "WAT" ~ "Hydroelectric",
      Energy.Source.1 == "WDS" ~ "Solid Renewable Fuel",
      Energy.Source.1 == "WH" ~ "Waste Heat",
      Energy.Source.1 == "WND" ~ "Wind",
      TRUE ~ "Unknown"
  ))

st_write(generatorsNc, "../Data/Processed/generatorsFuelType.geojson")

```


```{r}

generators = st_read("../Data/Processed/generators.geojson") %>%
  plyr::rename(., c(County.x="CountyShort")) %>% 
  st_transform(4269) %>%
  mutate(FuelType=case_when(
      Energy.Source.1 == "AB" ~ "Solid Renewable Fuel",
      Energy.Source.1 == "BIT" ~ "Coal",
      Energy.Source.1 == "BLQ" ~ "Liquid Renewable Fuel",
      Energy.Source.1 == "DFO" ~ "Petroleum Product",
      Energy.Source.1 == "LFG" ~ "Gaseous Renewable Fuel",
      Energy.Source.1 == "MWH" ~ "Energy Storage",
      Energy.Source.1 == "NG" ~ "Natural Gas",
      Energy.Source.1 == "NUC" ~ "Nuclear",
      Energy.Source.1 == "OBG" ~ "Gaseous Renewable Fuel",
      Energy.Source.1 == "SUN" ~ "Solar",
      Energy.Source.1 == "WAT" ~ "Hydroelectric",
      Energy.Source.1 == "WDS" ~ "Solid Renewable Fuel",
      Energy.Source.1 == "WH" ~ "Waste Heat",
      Energy.Source.1 == "WND" ~ "Wind",
      TRUE ~ "Unknown"
  ))

censusData2020 = censusData %>%
  filter(Year==2020)

st_crs(generators) == st_crs(censusData2020)

generatorsCensus = generators %>%
  st_join(censusData2020, join=st_contains, left=TRUE, largest=TRUE)

generatorsCensus = generatorsCensus %>%
  plyr::rename(., c(Utility.ID.x="Utility.ID",
                    Plant.Name.x="Plant.Name",
                    Utility.Name.x="Utility.Name",
                    CountyShort.x="County.Short")) %>%
  select(-ends_with(".y"), -State.x)

st_write(generatorsCensus, "../Data/Processed/generatorsCensus2020.geojson")

```